apiVersion : apps/v1
kind: Deployment
metadata:
  name: netology-task-2
  labels:
    app: task-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-1
  template:
    metadata:
      labels:
        app: task-1
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
          - mountPath: /share
            name: share-volume
      volumes:
      - name: share-volume
        persistentVolumeClaim:
          claimName: nfs-pvc